# Generated by Django 5.1.4 on 2025-01-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_address_alter_customuser_birth_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year_of_publication', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(max_length=50)),
            ],
        ),
    ]
